skillMetadata:
  sections:
    - name: Configuration
      fields:
        - name: pin_mode
          type: select
          label: Use GPIO number or pin number
          options: "BCM|bcm;BOARD|board"
          value: bcm
        - name: pin_number
          type: number
          label: PIN where the LED is connected to
          value: 23
          placeholder: "Example: 20"
